import Head from 'next/head'
import Image from 'next/image'
import IntroHeader from '@/components/IntroHeader'
import Projects from '@/components/Projects'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <IntroHeader />
      <Projects />
    </div>
  )
}
