import Head from 'next/head'
import Image from 'next/image'
import IntroHeader from '@/components/IntroHeader'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'

import LazyShow from '@/components/LazyShow'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <LazyShow>
        <IntroHeader />
      </LazyShow>
      <LazyShow>
        <Projects />
      </LazyShow>
      <LazyShow>
        <Contact />
      </LazyShow>
    </div>
  )
}
